### ISSUE TITLE
0.10.0 recognized the twitter bot but 0.15.0 does not

### ISSUE THREAD

**Issue by boatcoder** [ua-parser/uap-python#124]
```
TWITTER_BOT_USER_AGENT = (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4"
        " (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4"
        " facebookexternalhit/1.1 Facebot Twitterbot/1.0"
    )
```
This is no longer detected as `is_bot`

Maybe because of this not containing Facebot:
https://github.com/ua-parser/uap-core/blob/417c38ee44b9197d718d6663122882aa9e61a9b0/regexes.yaml#L124

```
  # Twitter
  - regex: '(Twitterbot)/(\d+)\.(\d+)'
    family_replacement: 'Twitterbot'
```

While parsing, these are the pieces that are found:
```
string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0
user_agent: {'family': 'FacebookBot', 'major': '1', 'minor': '1', 'patch': None}
os: {'family': 'Mac OS X', 'major': '10', 'minor': '11', 'patch': '1', 'patch_minor': None}
device: {'family': 'Mac', 'brand': 'Apple', 'model': 'Mac'}

So the user_agent family is `FacebookBot` but it still returns `False` for `is_bot`

**Comment by boatcoder** [comment]
I'm not sure if this had to do with a dirty cache.....

**Comment by masklinn** [comment]
Hello @boatcoder, regardless of whether the issue turns out to be a cache or a genuine error, issues with the regexes.yaml data should be reported to ua-parser/uap-core, ua-parser/uap-python simply provides an interface to that.

Unless it's that we're using an outdated version of the data file, and I see I'll have to update that to 0.16.
