### ISSUE TITLE
Snyk Security Vulnerabilities

### ISSUE THREAD

**Issue by DenizKucukozturk** [ua-parser/uap-python#141]
Snyk is flagging uap-python as insecure because of Regular Expression Denial of Service (ReDoS). Here it can be seen https://security.snyk.io/package/pip/ua-parser/0.16.1. Regex should be updated I guess

**Comment by masklinn** [comment]
Unclear what the issue is. As far as I can tell it seems to be ua-parser/uap-core#495 but that should be fixed since the release of 0.15 in May.

Either way, unless there are specific mitigations to implement (or the issue is specifically caused by Python's regex engine)  uap-python is "just" a frontend to uap-core's regex set, issues should be reported over there.
