### ISSUE TITLE
`LICENSE` is in a subdirectory

### ISSUE THREAD

**Issue by junyer** [ua-parser/uap-python#150]
The lawyer🐈s have advised me to try to tidy up a couple of things for compliance reasons:

* remove the `LICENSE` file from the `ua_parser` subdirectory;
* add a `LICENSE` file with the canonical [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt) text to the root directory; and
* remove the _Copyright_ section from `README.rst`.

`LICENSE` was moved to `ua_parser/LICENSE` back in June 2012 ostensibly for packaging reasons. Some brief tinkering leads me to believe that `setuptools` handles `license_files=['../LICENSE']` incorrectly, but that a symbolic link would work. Addressing the second point should enable GitHub (and related systems) to detect the licence automatically, which is why this conversation arose.

**Comment by masklinn** [comment]
> for compliance reasons

See comment on PR: what compliance reasons?

> LICENSE was moved to ua_parser/LICENSE back in June 2012 ostensibly for packaging reasons.

If you look at commit 1ef47432741e6904ffe32d8548a16b6bbb7c38e5 the entire contents of the repository was moved from the root to a sub-directory, which does make sense from a python semantics standpoint. It looks to me like the LICENSE file was just a casualty of everything being moved over, rather than that being the primary purpose of the change.

Before: https://github.com/ua-parser/uap-python/tree/d29580219e350b1a4552afce75ae563df37e17e0
After: https://github.com/ua-parser/uap-python/tree/1ef47432741e6904ffe32d8548a16b6bbb7c38e5

The "before" layout definitely is not what you'd normally expect from a python package, even circa 2012.

>  Some brief tinkering leads me to believe that setuptools handles `license_files=['../LICENSE']` incorrectly

Why would setuptools be told to look up the license files in the parent directory though?

**Comment by junyer** [comment]
IIUC, the primary problem is that the `LICENSE` file doesn't actually contain the licence – it's the boilerplate notice that would typically be placed at the top of a licensed file. Note that https://www.apache.org/licenses/LICENSE-2.0.txt section 4(a) says:

```
   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and
```
