### ISSUE TITLE
[request] simplified browser name

### ISSUE THREAD

**Issue by coolbombom** [ua-parser/uap-python#156]
Hi

Thank you for a great tool.

I was wondering if it is possible to add `browser` to user_agent, i know that i can see the family, but i really want to be able to see family `chrome mobile webview` and `chrome mobile` as just `chrome` browser instead of handling each family type.

And i don't think doing a contains is well written code and therefore something i would like to stay away from.

example:

uas `Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Mobile Safari/537.36` result in family = `chrome mobile`, version=87

uas `Mozilla/5.0 (Linux; Android 13; SM-S918B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.101 Mobile Safari/537.36` result in family = `chrome mobile webview`, version=112

But both instances are  `chrome` browser

kind regards
c_bb

**Comment by masklinn** [comment]
Heya, the project really implements the spec from https://github.com/ua-parser/uap-core, both the data being manipulated *and the data extraction directives* are defined over there, specifically [regexes.yaml](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml). So you'd need that feature to be added there, and then to the parsing spec.

Furthermore, because it uses a relatively limited subset of regular expressions (to limit incompatibilities), I'm not sure it would be feasible without adding the information explicitly to every rule (though I may be wrong). Finally this is a somewhat ambiguous feature as you'd need to resolve questions like "is Edge a Chrome" (after all they use the same browser engine) and "is Chrome Mobile for iOS a Chrome or a Safari" (it uses safari's engine, like every browser currently on the platform).

An alternative method would be to use regexes.yaml to look at the sort of families it outputs, and then classify it on your end.

Anyway as noted above that's more of a query / issue for the parent project linked above, so I'll be closing this.
