### ISSUE TITLE
Improve detection for certain browsers

### ISSUE THREAD

**Issue by ataylor32** [ua-parser/uap-python#211]
There are six browsers I know of that could use some improvement in their detection:

# Aloha

This browser is available on Windows, Android, and iOS. There is also a macOS version, but it's still in beta, so I haven't tested it.

Windows:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 AlohaBrowser/2.0.0.0 Safari/537.36
```

Android:

```
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36 AlohaBrowser/6.0.2
```

iOS:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Version/17.5.1 Safari/605.1.15 AlohaBrowser/5.11.0
```

# DuckDuckGo

This browser is available on Windows, macOS, Android, and iOS. The macOS and iOS versions are detectable:

macOS:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15 Ddg/17.3.1
```

iOS:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1 Ddg/17.5
```

# Ecosia

This browser is available on Windows, macOS, Android, and iOS. The Android and iOS versions are detectable:

Android:

```
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36 (Ecosia android@119)
```

iOS:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5.1 Mobile/15E148 Safari/604.1 (Ecosia ios@9.5.0.1569)
```

# Ghostery

This browser is available on Windows, macOS, Linux, Android, and iOS. The Android and iOS versions are detectable:

Android:

```
Mozilla/5.0 (Android 14; Mobile; rv:125.0; Ghostery:3.0) Gecko/125.0 Firefox/125.0
```

iOS:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/605.1.15 Ghostery Private Browser
```

# Opera

This browser is available on Windows, macOS, Linux, Android, and iOS. This script usually detects Opera, but it doesn't work for the iOS version:

iOS:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1 OPT/4.7.0
```

# Opera GX

This browser is available on Windows, macOS, Android, and iOS. The Android and iOS versions are detectable:

Android:

```
Mozilla/5.0 (Linux; Android 14; SM-G991U1 Build/UP1A.231005.007) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36 OPX/2.3
```

iOS:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1 OPX/2.5.0
```

**Comment by masklinn** [comment]
Heya, thanks for the report, however uap-python like the other uap implementations relies on the data from [ua-parser/uap-core](https://github.com/ua-parser/uap-core) for the classification and extraction, specifically [the `regexes.yaml` rules file](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml).

As such, if browsers are unidentified or misidentified it should be reported to [ua-parser/uap-core](https://github.com/ua-parser/uap-core) rather than here, unless the issue is that the packaged / precompiled file is outdated (but as far as I can tell core is still on 0.18 which should be what's packaged).

And as an aside, I would very strongly recommend checking the PRs and submitting fixes if there are none: the core maintainers have very variable availability, so issues which just drop unrecognised or misparsed UAs are unlikely to be prioritised.
