### ISSUE TITLE
Maintain history and version number consistency

### ISSUE THREAD

**Issue by beruic** [ua-parser/uap-python#30]
I just noticed that version 0.5.0 is available on pypi, so I went here looking for a chagelog. I cannot find one, and the code in the repository seems like it's still version 0.4.1, which is the version I currently use in my project.

I looked in uap-core and found version 0.5.0 under releases, but I was confused that there was no version 0.4.1 (only 0.4.0), and I still can't really find a good description of what has changed. Of course I can read the commit messages, but that is not very easily read.

All in all, I am hessitant to upgrade, because I am unsure of what has happened.

**Comment by elsigh** [comment]
No one using uap-python in a decent-size production environment has stepped up to deal with channel distribution. I'm going to close this (sorry) because it comes up a lot and it's a known issue. The reality is that github is up to date and until someone who loves the python distribution channels comes to the rescue this is likely to remain an issue.

**Comment by beruic** [comment]
Could you perhaps include a description about this in the README?
I can't say I fully understand the issue, but I guess the sum of it is that I will be fine upgrading?
