### ISSUE TITLE
ModuleNotFoundError: No module named 'ua_parser._regexes'

### ISSUE THREAD

**Issue by wjmj** [ua-parser/uap-python#62]
Hello,

I try to install ua-parser using 'pip install ua-parser' and manual install(python setup.py install), however, both issued the same error: ModuleNotFoundError: No module named 'ua_parser._regexes'. The following is the detail error message after I install ua-parser use pip.

Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ua_parser import user_agent_parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\ua\uap-python-master\uap-python-master\ua_parser\user_agent_parser.p
", line 552, in <module>
    from ._regexes import USER_AGENT_PARSERS, DEVICE_PARSERS, OS_PARSERS
ModuleNotFoundError: No module named 'ua_parser._regexes'

My os is win7 64bit. Is there something I missed?
Thanks for your attention.

**Comment by Zjion** [comment]
It happened to me. After running `python setup.py install`, you will get something like 

`running build`
`running build_regexes`
`running build_py`
`...`

if you look at the setup.py code, the program is supposed to parse the regexes.yaml file in uap-core to write a regexes.py file which is the module you are looking for.

You do not have this file because the `run` method returns after

`if not os.path.exists(os.path.join(work_path, '.git')):`
`            return`

The shortcut is to comment out these lines as well as 

`check_output(['git', 'submodule', 'init'], cwd=work_path)`
`check_output(['git', 'submodule', 'update'], cwd=work_path)`

and run `python setup.py install`
This should solve your problem for now. Maybe a PR later can address this issue.

**Comment by wjmj** [comment]
Thanks for your help, although I decided to use another ua parser.

**Comment by elsigh** [comment]
just closing cuz old
