### ISSUE TITLE
Make the API more pythonic (snake_case function names)

### ISSUE THREAD

**Issue by ThiefMaster** [ua-parser/uap-python#93]
Right now the whole API is using CamelCase which is extremely unpythonic. It would be nice if you could add snake_case alternatives, or even deprecated the old ones and eventuallt remove them.

**Comment by masklinn** [comment]
That matches my sensibilities, plus since the namespacing is a bit odd it should be easy to put a new API at the root of `uap_python`. I'll have to familiarise myself with the feature coverage (what's a useful part of the API, what's just incidental, ...) and get the project in a better shape before working on that though.

**Comment by masklinn** [comment]
Finally stopped putting off the merging of the new API so closing this, though it's quite far from release yet.
